.vscodeignore

A couple of new files crept into the vsix bundle

chore: Extra exclusions for vscode package

---

.github/workflows/ci.yml
.github/workflows/publish.yml
.gitignore
package-lock.json

Use `package-lock.json` & `npm ci` to ensure versions are consistent

chore: Add package lock for CI versioning

---

.eslintrc.json
src/client/extension.ts
src/server/beebasm-ts/lineparser.ts
src/server/server.ts
tsconfig.json

Just cleaning up a few lint issues.
Added eslint rule to allow underscore prefix to silence the unused var warnings

fix: Linting updates

---

src/client/extension.ts

fix: Fix target adding and switching

---

package-lock.json
package.json

fix: Typo in the extension title

---

assets/css/styles.css
src/client/panels/emulator-panel.ts
src/scripts/dom.ts
src/scripts/emulator-infobar.ts
src/scripts/emulator-view.ts
src/scripts/emulator.ts
src/scripts/index.ts

Now updates mode/runtime/text/gfx coords

feat: Emulator info bar

---

src/client/panels/emulator-panel.ts
src/scripts/emulator-infobar.ts
src/scripts/emulator-toolbar.ts
src/scripts/index.ts

All toolbar UI functionality now in `EmulatorToolBar` class

feat: Emulator toolbar

---

package-lock.json
package.json
src/scripts/custom-audio-handler.ts
src/scripts/emulator-toolbar.ts

View toolbar mute button now working.

feat: Support Mute/Unmute

---

src/scripts/emulator-toolbar.ts
src/scripts/emulator-view.ts
src/scripts/emulator.ts

Button now toggles emulator full or cropped CRT view

feat: Full screen display button

---

src/scripts/emulator-view.ts
src/scripts/emulator.ts
src/scripts/index.ts
src/types/jsbeeb/6502.d.ts
src/types/jsbeeb/via.d.ts

Simulate holding shift+BREAK when launch a disc image from context menu.

feat(emulator): Autoboot when launching from context menu

---

assets/css/styles.css
esbuild.config.js
src/client/panels/emulator-panel.ts
src/scripts/emulator-view.ts
src/scripts/vscode.ts

Now shows JSBeeb link:
Also:
* Fixed canvas aspect
* Canvas resolution always 720x576 PAL
* Canvas is scaled to fit outer container
* Cleanups of css and html

feat: Add JSBeeb link

---

assets/css/styles.css
assets/images/green-led-off.svg
assets/images/green-led-on.svg
assets/images/red-led-off.svg
assets/images/red-led-on.svg
src/client/panels/emulator-panel.ts
src/scripts/emulator-ledbar.ts
src/scripts/emulator-view.ts
src/scripts/emulator.ts
src/scripts/index.ts
src/types/jsbeeb/6502.d.ts
src/types/jsbeeb/acia.d.ts
src/types/jsbeeb/econet.d.ts
src/types/jsbeeb/fdc.d.ts
src/types/jsbeeb/models.d.ts

feat(emulator): Add led indicators

---

src/client/extension.ts
src/server/filehandler.ts
src/server/server.ts

feat: Refresh on change to settings.json

---

patches/jsbeeb+0.0.7.patch
src/client/panels/emulator-panel.ts
src/scripts/emulator-ledbar.ts
src/scripts/emulator.ts
src/scripts/index.ts
src/types/jsbeeb/utils.d.ts

Cleaned up the jsbeeb patch for overriding the `loadData` functions
Also improved the initial script loader exception handling

fix(emulator): JSBeeb patch improvements

---

package.json
src/client/extension.ts
src/client/panels/emulator-panel.ts
src/types/shared/config.ts

feat(emulator): Enable feature flag for production builds

---

esbuild.config.js

Language server dependencies need bundling with the package

fix: Bundle all deps except 'vscode'

---

src/client/extension.ts
src/server/beebasm-ts/lineparser.ts
src/server/filehandler.ts
src/server/server.ts

Resolve recent error with multi-root projects that don't have a settings.json created with the compile target(s) listed.

fix: Avoid errors without settings

---

src/server/ast.ts
src/server/beebasm-ts/lineparser.ts
src/server/beebasm-ts/macro.ts
src/server/beebasm-ts/sourcecode.ts
src/server/hoverprovider.ts
src/server/semantictokenprovider.ts
src/server/server.ts
src/server/symbolhandler.ts
src/server/test/tests.ts

Closes #94 
Adds standard reference functionality for macro calls (go to definition, find all references, hover shows macro definition).
Also introduces semantic token capability. Just for macro calls for now but have potential to add more features on top of this if we have any ideas.

feat: Macro handling

---

src/client/extension.ts

Fixes #101
If there is no settings.json (or there is but it has not beebvsc entry), then we parse the tasks.json file to look for any tasks that tell us what compile targets are passed to BeebASM and put them into the settings.json file. Tested to work with both the old 0.1.0 version of tasks.json and the current 2.0.0 version.

feat: Can build settings.json from tasks.json

---

src/client/test/runTest.ts

feat: E2E testing from command line

---

src/server/completions.ts
src/server/test/tests.ts

Don't show signature helper when in comments

---

src/server/completions.ts

Add opcodes and registers to autocomplete

---

src/server/beebasm-ts/lineparser.ts
src/server/beebasm-ts/objectcode.ts

Track if had second pass consistency error so only report once

---

src/client/extension.ts

Find targets regardless of case

---

package.json
src/client/extension.ts

chore: Add project identifier to commands

---

src/server/beebasm-ts/asmexception.ts
src/server/beebasm-ts/lineparser.ts
src/server/beebasm-ts/sourcecode.ts

Fixes #164 and #165 with minor edits

fix: Divide error and infinite for loop fixes
